name: Prebuild devcontainer

on:
  push:
    branches: ['main']
  workflow_dispatch:
  workflow_call:

env:
  DEVPOD_PREBUILD_REPO: ghcr.io/${{ github.repository_owner }}/devpod-cache

jobs:
  detect-variants:
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.set-matrix.outputs.variants }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          variants=$(printf '%s\n' */devcontainer.json | sed 's|/devcontainer.json||' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "variants=$variants" >> "$GITHUB_OUTPUT"

  prebuild-devcontainer:
    needs: detect-variants
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: ${{ fromJson(needs.detect-variants.outputs.variants) }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install devpod
        run: |
          curl -LO "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64"
          sudo install devpod-linux-amd64 /usr/local/bin/devpod

      - name: Devpod setup
        run: |
          devpod provider add docker
          devpod provider use docker

      - name: Prebuild variant
        run: devpod build . --devcontainer-path "./${{ matrix.variant }}/devcontainer.json"
